FROM ubuntu:utopic

# Install Apache 2:
RUN apt-get update && \
	apt-get -qy upgrade

# COPY /playapp/geopublisher-web.zip /opt/geopublisher-web.zip

# RUN unzip /opt/geopublisher-web.zip /opt/geopublisher-web/

# CMD ["/opt/geopublisher-web/bin/start.sh"]