FROM ubuntu:trusty

# Install Apache 2:
RUN apt-get update && \
	apt-get -qy upgrade && \
	apt-get -qy install && \
		unzip

# RUN wget geoserver.zip && \
# 		unzip geoserver.zip 	

# Configuratie

# Expose network ports:
# EXPOSE 8080

# CMD ["/path/to/geoserver.sh"]